-- ============================================================================
-- MusicBrainz Import — Step 3: Transform staging data into demo schema
-- ============================================================================
-- ⚠️  THIS FILE IS KEPT FOR REFERENCE ONLY.  It is no longer executed directly.
--
-- The import workflow (.github/workflows/import-musicbrainz.yml) now runs the
-- transform in multiple separate psql sessions to avoid Azure PostgreSQL
-- killing long-running connections:
--
--   1. mb_staging_load_setup.sql   — truncate + core entity tables
--   2. Shell loop                  — batch-insert recording (500 K rows/batch)
--   3. mb_staging_load_tables.sql  — remaining entity, supporting & link tables
--   4. Shell loop                  — batch-insert l_artist_recording
--   5. mb_staging_load_finish.sql  — final link tables, re-enable triggers,
--                                    drop staging schema
--
-- Each batch INSERT runs in its own psql connection (~5-10 s each), so no
-- single session exceeds Azure's connection-duration limits.
-- ============================================================================
