/**
 * Backfill status read-only endpoints.
 *
 * Exposes recent runs from `musicbrainz.backfill_progress` so operators
 * can inspect progress from anywhere (web UI, CLI via `curl`, monitoring
 * dashboards) without needing direct PostgreSQL access.
 *
 *   GET /api/backfill/status                 — list recent runs
 *   GET /api/backfill/status/:runId          — fetch a single run
 *
 * Returns `{ available: false }` (200) when PostgreSQL is not configured
 * so callers can render an empty state instead of erroring out.
 */
import { Router } from 'express';
import { isPgAvailable, query } from '../db/pgClient.js';

export const backfillStatusRouter = Router();

interface RunRow {
  run_id: string;
  entity: string;
  status: string;
  started_at: string;
  finished_at: string | null;
  last_heartbeat_at: string;
  processed: string;
  embedded: string;
  skipped: string;
  errors: string;
  last_id: string;
  min_id: string;
  max_id: string | null;
  batch_size: number | null;
  concurrency: number | null;
  message: string | null;
}

function shapeRun(r: RunRow): Record<string, unknown> {
  const startedAt = new Date(r.started_at).getTime();
  const lastBeat = new Date(r.last_heartbeat_at).getTime();
  const elapsedSec = Math.max(1, Math.round((lastBeat - startedAt) / 1000));
  const processed = parseInt(r.processed, 10);
  const ratePerSec = elapsedSec > 0 ? processed / elapsedSec : 0;
  return {
    runId: r.run_id,
    entity: r.entity,
    status: r.status,
    startedAt: r.started_at,
    finishedAt: r.finished_at,
    lastHeartbeatAt: r.last_heartbeat_at,
    processed,
    embedded: parseInt(r.embedded, 10),
    skipped: parseInt(r.skipped, 10),
    errors: parseInt(r.errors, 10),
    lastId: parseInt(r.last_id, 10),
    minId: parseInt(r.min_id, 10),
    maxId: r.max_id === null ? null : parseInt(r.max_id, 10),
    batchSize: r.batch_size,
    concurrency: r.concurrency,
    message: r.message,
    elapsedSeconds: elapsedSec,
    ratePerSecond: Number(ratePerSec.toFixed(2)),
  };
}

backfillStatusRouter.get('/backfill/status', async (req, res) => {
  if (!isPgAvailable()) {
    res.json({ available: false, runs: [] });
    return;
  }

  // Cap the limit; reject anything that doesn't parse to a small integer.
  const rawLimit = req.query.limit;
  let limit = 20;
  if (typeof rawLimit === 'string') {
    const n = parseInt(rawLimit, 10);
    if (Number.isFinite(n) && n > 0 && n <= 100) limit = n;
  }

  try {
    const rows = await query<RunRow>(
      `SELECT run_id, entity, status, started_at, finished_at,
              last_heartbeat_at,
              processed::text AS processed,
              embedded::text  AS embedded,
              skipped::text   AS skipped,
              errors::text    AS errors,
              last_id::text   AS last_id,
              min_id::text    AS min_id,
              max_id::text    AS max_id,
              batch_size, concurrency, message
         FROM musicbrainz.backfill_progress
        ORDER BY started_at DESC
        LIMIT $1`,
      [limit],
    );
    res.json({ available: true, runs: rows.map(shapeRun) });
  } catch (err) {
    // Most likely cause: progress table doesn't exist yet (no backfill has
    // ever run). Return an empty list rather than 500-ing.
    const code = (err as { code?: string }).code;
    if (code === '42P01') {
      res.json({ available: true, runs: [] });
      return;
    }
    console.error('[backfill/status] query failed:', err);
    res.status(500).json({ error: 'Failed to read backfill progress' });
  }
});

backfillStatusRouter.get('/backfill/status/:runId', async (req, res) => {
  if (!isPgAvailable()) {
    res.json({ available: false });
    return;
  }
  const { runId } = req.params;
  // Run ids are generated by Azure (`<job>--<exec-id>`) or by us (UUID).
  // Keep input shape narrow to defend against odd characters.
  if (!/^[A-Za-z0-9._-]{1,128}$/.test(runId)) {
    res.status(400).json({ error: 'Invalid run id' });
    return;
  }
  try {
    const rows = await query<RunRow>(
      `SELECT run_id, entity, status, started_at, finished_at,
              last_heartbeat_at,
              processed::text AS processed,
              embedded::text  AS embedded,
              skipped::text   AS skipped,
              errors::text    AS errors,
              last_id::text   AS last_id,
              min_id::text    AS min_id,
              max_id::text    AS max_id,
              batch_size, concurrency, message
         FROM musicbrainz.backfill_progress
        WHERE run_id = $1`,
      [runId],
    );
    if (rows.length === 0) {
      res.status(404).json({ error: 'Run not found' });
      return;
    }
    res.json({ available: true, run: shapeRun(rows[0]) });
  } catch (err) {
    const code = (err as { code?: string }).code;
    if (code === '42P01') {
      res.status(404).json({ error: 'Run not found' });
      return;
    }
    console.error('[backfill/status] query failed:', err);
    res.status(500).json({ error: 'Failed to read backfill progress' });
  }
});
